export const easeMap = {
    quadraticIn: 1,
    quadraticOut: 1.1,
    quadraticInOut: 1.2,
    cubicIn: 2,
    cubicOut: 2.1,
    cubicInOut: 2.2,
    quarticIn: 3,
    quarticOut: 3.1,
    quarticInOut: 3.2,
    // quinticIn: 4,
    // quinticOut: 4.1,
    // quinticInOut: 4.2,
    circularIn: 4,
    circularOut: 4.1,
    circularInOut: 4.2,
    exponentialIn: 5,
    exponentialOut: 5.1,
    exponentialInOut: 5.2,
    sineIn: 6,
    sineOut: 6.1,
    sineInOut: 6.2,
}
